name: Gradle Dependencies

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  list-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: List Dependencies
      run: gradle dependencies > dependencies.txt

    - name: Upload Dependencies
      uses: actions/upload-artifact@v3
      with:
        name: dependencies
        path: dependencies.txt
